{ pkgs, lib, ... }:
let
  inherit (lib) mkOption types;

  timeoutsSubmodule = types.submodule {
    options = {
      connect = mkOption {
        description = ''
          TCP dial connection timeout in seconds
        '';
        type = types.ints.unsigned;
        default = 30;
      };
      keepalive = mkOption {
        description = ''
          TCP connection keepalive timeout in seconds
        '';
        type = types.ints.unsigned;
        default = 30;
      };
      responseHeader = mkOption {
        description = ''
          Time to wait for response headers in seconds
        '';
        type = types.ints.unsigned;
        default = 0;
      };
      tlsHandshake = mkOption {
        description = ''
          TLS handshake timeout in seconds
        '';
        type = types.ints.unsigned;
        default = 10;
      };
      idleConn = mkOption {
        description = ''
          Idle connection timeout in seconds
        '';
        type = types.ints.unsigned;
        default = 90;
      };
    };
  };

  capabilitiesSubmodule = types.submodule {
    options = {
      "in" = mkOption {
        description = ''
          List of modalities understood by the model
        '';
        type = types.listOf (
          types.enum [
            "text"
            "audio"
            "image"
          ]
        );
        default = [ ];
      };
      out = mkOption {
        description = ''
          List of modalities generated by the model
        '';
        type = types.listOf (
          types.enum [
            "text"
            "audio"
            "image"
          ]
        );
        default = [ ];
      };
      tools = mkOption {
        description = ''
          Whether the model supports function calling
        '';
        type = types.bool;
        default = false;
      };
      reranker = mkOption {
        description = ''
          Whether the model supports the /v1/rerank endpoint
        '';
        type = types.bool;
        default = false;
      };
      context = mkOption {
        description = ''
          Maximum token context length supported, must be an integer > 0
        '';
        type = types.ints.unsigned;
        default = 0;
      };
    };
  };

  modelFiltersSubmodule = types.submodule {
    options = {
      stripParams = mkOption {
        description = ''
          Comma separated list of parameters to remove from the request.
          Useful for server side enforcement of sampling parameters. The
          `model` parameter can never be removed
        '';
        type = types.str;
        default = "";
      };
      setParams = mkOption {
        description = ''
          Dictionary of parameters to set/override in requests. Useful for
          enforcing specific parameter values. Protected params like "model"
          cannot be overridden. Always runs for the model
        '';
        type = types.attrsOf types.anything;
        default = { };
      };
      setParamsByID = mkOption {
        description = ''
          Dictionary of parameters to set based on the model ID. Combine
          with aliases to create variant behaviour without reloading the
          model. Run after setParams so it will override any settings.
          Protected params like "model" cannot be overridden. Model aliases
          will be automatically created for each key
        '';
        type = types.attrsOf (types.attrsOf types.anything);
        default = { };
      };
    };
  };

  peerFiltersSubmodule = types.submodule {
    options = {
      stripParams = mkOption {
        description = ''
          Comma separated list of parameters to remove from the request.
          Useful for removing parameters that the peer doesn't support. The
          `model` parameter can never be removed
        '';
        type = types.str;
        default = "";
      };
      setParams = mkOption {
        description = ''
          Dictionary of parameters to set/override in requests to this
          peer. Useful for injecting provider-specific settings. Protected
          params like "model" cannot be overridden
        '';
        type = types.attrsOf types.anything;
        default = { };
      };
    };
  };

  modelSubmodule = types.submodule {
    options = {
      macros = mkOption {
        description = ''
          Dictionary of string substitutions specific to this model.
          Macros defined here override macros defined in the global macros
          section. Model level macros follow the same rules as global
          macros
        '';
        type = types.attrsOf (
          types.oneOf [
            types.str
            types.int
            types.float
            types.bool
          ]
        );
        default = { };
      };
      cmd = mkOption {
        description = ''
          The command to run to start the inference server
        '';
        type = types.str;
      };
      name = mkOption {
        description = ''
          A display name for the model. If set, it will be used in the
          v1/models API response. If not set, it will be omitted in the
          JSON model record
        '';
        type = types.str;
        default = "";
      };
      description = mkOption {
        description = ''
          A description for the model. If set, it will be used in the
          v1/models API response. If not set, it will be omitted in the
          JSON model record
        '';
        type = types.str;
        default = "";
      };
      env = mkOption {
        description = ''
          Array of environment variables to inject into cmd's environment,
          in the format: ENV_NAME=value
        '';
        type = types.listOf types.str;
        default = [ ];
      };
      proxy = mkOption {
        description = ''
          The URL where llama-swap routes API requests. If you use
          a custom port in cmd this *must* be set
        '';
        type = types.str;
      };
      checkEndpoint = mkOption {
        description = ''
          URL path to check if the server is ready. Endpoint is expected
          to return an HTTP 200 response. All requests wait until the
          endpoint is ready or fails. Use "none" to skip endpoint health
          checking
        '';
        type = types.str;
        default = "/health";
      };
      ttl = mkOption {
        description = ''
          Automatically unload the model after ttl seconds. Must be >= -1.
          A ttl of -1 will use the global TTL value as the default. A ttl
          of 0 means never unload
        '';
        type = types.int;
        default = -1;
      };
      unloadTimeout = mkOption {
        description = ''
          Graceful timeout in seconds when unloading this model (manual,
          API, or ttl expiry), used before force-killing the model
          process. A value of 0 uses the global unloadTimeout. Useful for
          slow cmdStop commands such as docker stop
        '';
        type = types.ints.unsigned;
        default = 0;
      };
      useModelName = mkOption {
        description = ''
          Override the model name that is sent to upstream server. Useful
          for when the upstream server expects a specific model name that
          is different from the model's ID
        '';
        type = types.str;
        default = "";
      };
      filters = mkOption {
        description = ''
          Dictionary of filter settings. Same capabilities as peer filters
          (stripParams, setParams) plus setParamsByID
        '';
        type = modelFiltersSubmodule;
        default = { };
      };
      aliases = mkOption {
        description = ''
          Alternative model names that this model configuration is used
          for. Aliases must be unique globally. Useful for impersonating a
          specific model
        '';
        type = types.listOf types.str;
        default = [ ];
      };
      metadata = mkOption {
        description = ''
          Dictionary of arbitrary values that are included in /v1/models.
          While metadata can contain complex types it is recommended to
          keep it simple. Metadata is only passed through in /v1/models
          responses
        '';
        type = types.attrsOf types.anything;
        default = { };
      };
      concurrencyLimit = mkOption {
        description = ''
          Overrides the allowed number of active parallel requests to a
          model. Any number greater than 0 will override the internal
          default value of 10. Requests exceeding the limit receive an
          HTTP 429 Too Many Requests response. Recommended to be omitted
          and the default used
        '';
        type = types.ints.unsigned;
        default = 0;
      };
      sendLoadingState = mkOption {
        description = ''
          Overrides the global sendLoadingState setting for this model
        '';
        type = types.nullOr types.bool;
        default = null;
      };

      timeouts = mkOption {
        description = ''
          Configure proxy connection timeouts for this model. Useful for
          models running on slower hardware that need longer timeouts. Set
          any value to 0 to disable that timeout (not recommended)
        '';
        type = timeoutsSubmodule;
        default = { };
      };
      capabilities = mkOption {
        description = ''
          Defines what the model accepts for input, output and other
          metadata. Omitted or all-zero means no capabilities. Used in
          v1/models to inform clients what the model can do
        '';
        type = capabilitiesSubmodule;
        default = { };
      };
      unlisted = mkOption {
        description = ''
          Unlisted models do not show up in /v1/models api requests. Can
          be requested as normal through all apis
        '';
        type = types.bool;
        default = false;
      };
      cmdStop = mkOption {
        description = ''
          Command to run to stop the model gracefully. Useful for
          stopping commands managed by another system. The upstream's
          process id is available in the ''${PID} macro. When empty,
          llama-swap sends a SIGTERM on POSIX systems or calls taskkill on
          Windows
        '';
        type = types.str;
        default = "";
      };
    };
  };

  profileSubmodule = types.submodule {
    options = {
      description = mkOption {
        description = ''
          A description for the profile
        '';
        type = types.str;
        default = "";
      };
      pins = mkOption {
        description = ''
          Named model ID replacements switched at runtime through the UI
          or API. Targets may be a local model, peer model, alias, or
          setParamsByID alias. An empty string or null disables the pin
          with a 404
        '';
        type = types.attrsOf (types.nullOr types.str);
        default = { };
      };
    };
  };

  groupSubmodule = types.submodule {
    options = {
      swap = mkOption {
        description = ''
          How members of this group swap among themselves. true: only one
          member runs at a time. false: all members can run together, no
          swapping
        '';
        type = types.bool;
        default = true;
      };
      exclusive = mkOption {
        description = ''
          How this group affects other groups. true: running a member
          unloads every other group. false: running a member leaves other
          groups untouched
        '';
        type = types.bool;
        default = true;
      };
      persistent = mkOption {
        description = ''
          Other groups cannot unload this group's members. Has no effect
          on swapping within the group
        '';
        type = types.bool;
        default = false;
      };
      members = mkOption {
        description = ''
          The model IDs in this group. A model can belong to only one
          group
        '';
        type = types.listOf types.str;
      };
    };
  };

  matrixSubmodule = types.submodule {
    options = {
      vars = mkOption {
        description = ''
          Short aliases (alphanumeric, 1-8 chars) mapping to real model
          IDs (not model aliases). Keeps set expressions short and
          readable. Sets and evict_costs reference these names
        '';
        type = types.attrsOf types.str;
        default = { };
      };
      evict_costs = mkOption {
        description = ''
          Relative cost of losing a running model
        '';
        type = types.attrsOf types.int;
        default = { };
      };
      sets = mkOption {
        description = ''
          Named combinations of models that may run together, built from
          the expression language operators: & (AND), | (OR), ()
          (grouping), +ref (inline another set's expression)
        '';
        type = types.attrsOf types.str;
        default = { };
      };
    };
  };

  routerSubmodule = types.submodule {
    options = {
      use = mkOption {
        description = ''
          Which swap engine to use. group: simpler to configure, define
          groups of models that run together. matrix: more involved to
          configure, but far more flexible using a small expression
          language
        '';
        type = types.enum [
          "group"
          "matrix"
        ];
        default = "group";
      };
      settings = mkOption {
        description = ''
          Settings for the specific routing engine selected by `use`
        '';
        type = types.submodule {
          options = {
            groups = mkOption {
              description = ''
                Dictionary of named groups. Lets you keep some models
                loaded while others swap out. Every member must be a
                model ID defined in the models section
              '';
              type = types.attrsOf groupSubmodule;
              default = { };
            };
            matrix = mkOption {
              description = ''
                Lists the model combinations that are allowed to run
                concurrently. When a model is requested, the solver makes
                room for it by evicting as few running models as
                possible, preferring to keep the costliest ones loaded
              '';
              type = matrixSubmodule;
              default = { };
            };
          };
        };
        default = { };
      };
    };
  };

  schedulerSubmodule = types.submodule {
    options = {
      use = mkOption {
        description = ''
          How queued requests are ordered. The default and only valid
          scheduler is "fifo"
        '';
        type = types.enum [ "fifo" ];
        default = "fifo";
      };
      settings = mkOption {
        description = ''
          Settings for the specific scheduler selected by `use`
        '';
        type = types.submodule {
          options = {
            fifo = mkOption {
              description = ''
                Settings for the fifo scheduler
              '';
              type = types.submodule {
                options = {
                  priority = mkOption {
                    description = ''
                      Dictionary of model ID -> priority. Models default
                      to priority 0. Higher priority requests are
                      serviced first in the queue
                    '';
                    type = types.attrsOf types.int;
                    default = { };
                  };
                };
              };
              default = { };
            };
          };
        };
        default = { };
      };
    };
  };

  peerSubmodule = types.submodule {
    options = {
      proxy = mkOption {
        description = ''
          A valid base URL to proxy requests to. The requested path to
          llama-swap will be appended to the end of the proxy value
        '';
        type = types.str;
      };
      models = mkOption {
        description = ''
          List of models served by the peer
        '';
        type = types.listOf types.str;
      };
      apiKey = mkOption {
        description = ''
          A string key to be injected into the request. If blank, no key
          will be added to the request. Key will be injected into
          headers: Authorization: Bearer <key> and x-api-key: <key>
        '';
        type = types.str;
        default = "";
      };
      timeouts = mkOption {
        description = ''
          Configure proxy connection timeouts for this peer. Useful when
          the peer runs on slower hardware. Set any value to 0 to disable
          that timeout (not recommended)
        '';
        type = timeoutsSubmodule;
        default = { };
      };
      filters = mkOption {
        description = ''
          Dictionary of filter settings for peer requests. Same
          capabilities as model filters (stripParams, setParams)
        '';
        type = peerFiltersSubmodule;
        default = { };
      };
    };
  };
in
{
  _class = "llama-swap";

  options = {
    healthCheckTimeout = mkOption {
      description = ''
        Number of seconds to wait for a model to be ready to serve
        requests. Minimum value is 15 seconds, anything less will be set
        to this value
      '';
      type = types.ints.unsigned;
      default = 120;
    };

    logLevel = mkOption {
      description = ''
        Sets the logging value
      '';
      type = types.enum [
        "debug"
        "info"
        "warn"
        "error"
      ];
      default = "info";
    };

    logTimeFormat = mkOption {
      description = ''
        Enables and sets the logging timestamp format. See
        https://pkg.go.dev/time#pkg-constants for more info
      '';
      type = types.enum [
        ""
        "ansic"
        "unixdate"
        "rubydate"
        "rfc822"
        "rfc822z"
        "rfc850"
        "rfc1123"
        "rfc1123z"
        "rfc3339"
        "rfc3339nano"
        "kitchen"
        "stamp"
        "stampmilli"
        "stampmicro"
        "stampnano"
      ];
      default = "";
    };

    logToStdout = mkOption {
      description = ''
        Controls what is logged to stdout. "proxy": logs generated by
        llama-swap when swapping models, handling requests, etc.
        "upstream": a copy of an upstream process's stdout logs. "both":
        both the proxy and upstream logs interleaved together. "none": no
        logs are ever written to stdout
      '';
      type = types.enum [
        "proxy"
        "upstream"
        "both"
        "none"
      ];
      default = "proxy";
    };

    store = mkOption {
      description = ''
        Persistent storage for activity metrics state. File-backed sqlite
        keeps activity logs across restarts. Default (disabled) is an
        in-memory sqlite database capped by metricsMaxInMemory
      '';
      type = types.nullOr (
        types.submodule {
          options = {
            path = mkOption {
              description = ''
                Sqlite database file path
              '';
              type = types.str;
            };
          };
        }
      );
      default = null;
    };

    metricsMaxInMemory = mkOption {
      description = ''
        Maximum number of metrics to keep in memory before older ones are
        discarded. Useful for limiting memory usage when processing large
        volumes of metrics. When persistent sqlite storage is defined in
        store.path this has no effect
      '';
      type = types.ints.unsigned;
      default = 1000;
    };

    captureBuffer = mkOption {
      description = ''
        How many MBs to allocate for storing request/response captures.
        Set to 0 to disable
      '';
      type = types.ints.unsigned;
      default = 10;
    };

    ui = mkOption {
      description = ''
        UI-related settings
      '';
      type = types.submodule {
        options = {
          activity = mkOption {
            description = ''
              Settings for the Activity page
            '';
            type = types.submodule {
              options = {
                session_id = mkOption {
                  description = ''
                    Ordered request headers used to identify sessions in
                    the Activity page's in-flight request table. Matching
                    is case-insensitive; the first non-empty matching
                    header is shown. Set to [] to disable session ID
                    lookup
                  '';
                  type = types.listOf types.str;
                  default = [
                    "X-Session-ID"
                    "X-Litellm-Session-Id"
                  ];
                };
              };
            };
            default = { };
          };
        };
      };
      default = { };
    };

    performance = mkOption {
      description = ''
        Configuration for system monitoring statistics
      '';
      type = types.submodule {
        options = {
          disabled = mkOption {
            description = ''
              Whether performance monitoring is disabled
            '';
            type = types.bool;
            default = false;
          };
          every = mkOption {
            description = ''
              Delay between polling for new performance statistics.
              Duration string like 1s, 1h30m, 90m, 2h10s, etc. Minimum
              duration 5s
            '';
            type = types.str;
            default = "5s";
          };
        };
      };
      default = { };
    };

    sendLoadingState = mkOption {
      description = ''
        Inject loading status updates into the reasoning (thinking)
        field. When true, a stream of loading messages will be sent to
        the client in the reasoning field so chat UIs can show that
        loading is in progress
      '';
      type = types.bool;
      default = false;
    };

    includeAliasesInList = mkOption {
      description = ''
        Present aliases within the /v1/models OpenAI API listing. When
        true, model aliases will be output to the API model listing
        duplicating all fields except for Id so chat UIs can use the
        alias equivalent to the original
      '';
      type = types.bool;
      default = false;
    };

    globalTTL = mkOption {
      description = ''
        The default TTL in seconds before unloading a model. Must be >=
        0. A value of 0 means never automatically unload
      '';
      type = types.ints.unsigned;
      default = 0;
    };

    unloadTimeout = mkOption {
      description = ''
        Graceful timeout in seconds when unloading a model (manual, API,
        or ttl expiry), used before force-killing the model process on
        unload. Can be overridden per model with model.unloadTimeout.
        Large values extend how long an unload can take when a process
        does not exit cleanly
      '';
      type = types.ints.unsigned;
      default = 10;
    };

    macros = mkOption {
      description = ''
        Dictionary of string substitutions. Macros are reusable snippets
        used in a model's cmd, cmdStop, proxy, checkEndpoint,
        filters.stripParams. Macro names must be less than 64 characters,
        match the regex ^[a-zA-Z0-9_-]+$ and must not be a reserved name
        (PORT or MODEL_ID). Macros can contain other macros, but they
        must be defined before they are used. Environment variables can
        be referenced with ''${env.VAR_NAME} syntax and are substituted
        before regular macros
      '';
      type = types.attrsOf (
        types.oneOf [
          types.str
          types.int
          types.float
          types.bool
        ]
      );
      default = { };
    };

    apiKeys = mkOption {
      description = ''
        Require an API key when making requests to inference endpoints.
        When empty (the default) authorization will not be checked as
        llama-swap is default-allow. Each key must be a non-empty string
      '';
      type = types.listOf types.str;
      default = [ ];
    };

    upstream = mkOption {
      description = ''
        Controls behaviour of the /upstream passthrough endpoint.
        Recommended to only use in special use cases. Leaving it as the
        default will typically be the best experience
      '';
      type = types.submodule {
        options = {
          ignorePaths = mkOption {
            description = ''
              List of RE2 compatible regular expressions. Any request to
              a path matching any of the regular expressions will be
              ignored and not trigger a swap
            '';
            type = types.listOf types.str;
            default = [ ''.*\.(js|json|css|png|gif|jpg|jpeg|ico|txt)$'' ];
          };
        };
      };
      default = { };
    };

    profiles = mkOption {
      description = ''
        Named model ID replacements switched at runtime through the UI or
        API. One profile or none is active; startup and configuration
        reload select none. Pins are applied before aliases, filters, and
        routing
      '';
      type = types.attrsOf profileSubmodule;
      default = { };
    };

    models = mkOption {
      description = ''
        Dictionary of model configurations. Each key is the model's ID,
        used in API requests. Model settings have default values that
        are used if they are not defined here. The model's ID is
        available in the ''${MODEL_ID} macro, also available in macros
        defined above
      '';
      type = types.attrsOf modelSubmodule;
    };

    hooks = mkOption {
      description = ''
        Dictionary of event triggers and actions. The only supported hook
        is on_startup
      '';
      type = types.submodule {
        options = {
          on_startup = mkOption {
            description = ''
              Dictionary of actions to perform on startup. The only
              supported action is preload
            '';
            type = types.submodule {
              options = {
                preload = mkOption {
                  description = ''
                    List of model ids to load on startup. Model names
                    must match keys in the models section. When
                    preloading multiple models at once, define a group
                    otherwise models will be loaded and swapped out
                  '';
                  type = types.listOf types.str;
                  default = [ ];
                };
              };
            };
            default = { };
          };
        };
      };
      default = { };
    };

    routing = mkOption {
      description = ''
        Controls how llama-swap decides which models can run at the same
        time and which get swapped out
      '';
      type = types.submodule {
        options = {
          router = mkOption {
            description = ''
              Defines which swap engine is used and its settings
            '';
            type = routerSubmodule;
            default = { };
          };
          scheduler = mkOption {
            description = ''
              Defines how queued requests are ordered
            '';
            type = schedulerSubmodule;
            default = { };
          };
        };
      };
      default = { };
    };

    peers = mkOption {
      description = ''
        Dictionary of remote peers and models they provide. Peers can be
        another llama-swap, or any server that provides the /v1/
        generative api endpoints supported by llama-swap. Each key is the
        peer's ID
      '';
      type = types.attrsOf peerSubmodule;
      default = { };
    };
  };
}
